# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/clyde/cs225a/homework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/clyde/cs225a/homework/laundre

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clyde/cs225a/homework/laundre/CMakeFiles /home/clyde/cs225a/homework/laundre/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clyde/cs225a/homework/laundre/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw0-viz

# Build rule for target.
hw0-viz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw0-viz
.PHONY : hw0-viz

# fast build rule for target.
hw0-viz/fast:
	$(MAKE) -f hw0/CMakeFiles/hw0-viz.dir/build.make hw0/CMakeFiles/hw0-viz.dir/build
.PHONY : hw0-viz/fast

#=============================================================================
# Target rules for targets named hw0

# Build rule for target.
hw0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw0
.PHONY : hw0

# fast build rule for target.
hw0/fast:
	$(MAKE) -f hw0/CMakeFiles/hw0.dir/build.make hw0/CMakeFiles/hw0.dir/build
.PHONY : hw0/fast

#=============================================================================
# Target rules for targets named hw1-simviz

# Build rule for target.
hw1-simviz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw1-simviz
.PHONY : hw1-simviz

# fast build rule for target.
hw1-simviz/fast:
	$(MAKE) -f hw1/CMakeFiles/hw1-simviz.dir/build.make hw1/CMakeFiles/hw1-simviz.dir/build
.PHONY : hw1-simviz/fast

#=============================================================================
# Target rules for targets named hw1

# Build rule for target.
hw1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw1
.PHONY : hw1

# fast build rule for target.
hw1/fast:
	$(MAKE) -f hw1/CMakeFiles/hw1.dir/build.make hw1/CMakeFiles/hw1.dir/build
.PHONY : hw1/fast

#=============================================================================
# Target rules for targets named hw2-simviz

# Build rule for target.
hw2-simviz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw2-simviz
.PHONY : hw2-simviz

# fast build rule for target.
hw2-simviz/fast:
	$(MAKE) -f hw2/CMakeFiles/hw2-simviz.dir/build.make hw2/CMakeFiles/hw2-simviz.dir/build
.PHONY : hw2-simviz/fast

#=============================================================================
# Target rules for targets named hw2

# Build rule for target.
hw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw2
.PHONY : hw2

# fast build rule for target.
hw2/fast:
	$(MAKE) -f hw2/CMakeFiles/hw2.dir/build.make hw2/CMakeFiles/hw2.dir/build
.PHONY : hw2/fast

#=============================================================================
# Target rules for targets named hw3-simviz

# Build rule for target.
hw3-simviz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3-simviz
.PHONY : hw3-simviz

# fast build rule for target.
hw3-simviz/fast:
	$(MAKE) -f hw3/CMakeFiles/hw3-simviz.dir/build.make hw3/CMakeFiles/hw3-simviz.dir/build
.PHONY : hw3-simviz/fast

#=============================================================================
# Target rules for targets named hw3

# Build rule for target.
hw3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3
.PHONY : hw3

# fast build rule for target.
hw3/fast:
	$(MAKE) -f hw3/CMakeFiles/hw3.dir/build.make hw3/CMakeFiles/hw3.dir/build
.PHONY : hw3/fast

#=============================================================================
# Target rules for targets named project-simviz

# Build rule for target.
project-simviz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project-simviz
.PHONY : project-simviz

# fast build rule for target.
project-simviz/fast:
	$(MAKE) -f laundre/CMakeFiles/project-simviz.dir/build.make laundre/CMakeFiles/project-simviz.dir/build
.PHONY : project-simviz/fast

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) -f laundre/CMakeFiles/project.dir/build.make laundre/CMakeFiles/project.dir/build
.PHONY : project/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hw0-viz"
	@echo "... hw0"
	@echo "... hw1-simviz"
	@echo "... hw1"
	@echo "... hw2-simviz"
	@echo "... hw2"
	@echo "... hw3-simviz"
	@echo "... hw3"
	@echo "... project-simviz"
	@echo "... project"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

